require 'spec_helper'
require 'helpers/policies_helper'

RSpec.configure { |c| c.include PoliciesHelper }

describe Havox::Policies do
  describe '.run' do
    it 'outputs user-issued command results' do
      pending 'Write this test'
      expect(true).to be false
    end
  end

  describe '.compile' do
    let(:rule) { FactoryGirl.build :rule }

    it 'returns a set of parsed rules generated by Merlin' do
      allow(subject).to receive(:run).and_return(merlin_response)
      rules = subject.compile('/foo.dot', 'foo.mln')
      expect(rules.map(&:dp_id)).to include(rule.dp_id)
      expect(rules.map(&:matches)).to include(rule.matches)
      expect(rules.map(&:action)).to include(rule.action)
    end
  end
end
