require 'spec_helper'

describe Havox::Policies do
  describe '.run' do
    it 'outputs user-issued command results' do
      pending 'Write this test'
      expect(true).to be false
    end
  end

  describe '.compile' do
    it 'returns a set of parsed rules generated by Merlin' do
      pending 'Write this test'
      expect(true).to be false
    end
  end
end
